name: health-check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check out Git repository
      uses: actions/checkout@v2
    - uses: olegtarasov/get-tag@v2
      id: tagName
    - name: Install Java and Maven
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Package Beer-service
      run: |
        mvn -Pprod -DskipTests verify jib:dockerBuild --file=beer-api/pom.xml
        docker tag beer_api grc.io/tavern-meetup/beer-service:$GIT_TAG_NAME
    
    # - name: Publish to Registry
    #   uses: HurricanKai/Publish-Docker-Github-Action@master
    #   if: contains(github.ref, 'refs/tags/v')
    #   with:
    #     name: grc.io/tavern-meetup/beer-service:$GIT_TAG_NAME
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     # registry: grc.io
    #     tagging: true
    # - name: GitHub Action for Maven
    #   uses: LucaFeger/action-maven-cli@1.1.0
    #   args: -Pprod verify jib:dockerBuild --file beer-api/pom.xml

    - name: Deploy service to Cloud Run
      uses: stefda/action-cloud-run@1.0.0
      with:
        image: grc.io/tavern-meetup/beer-service:$GIT_TAG_NAME
        service: beer-service
        project: tavern-meetup
        region: europe-west1
        # env: [path-to-env-file]
        service key: ${{ secrets.GCLOUD_AUTH }}

  test:   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with Pytest
      run: |
        sudo pip install pytest
        sudo pip install pytest-html==1.22.0
        sudo pip install tavern
        sudo pip install pytest-sugar
        sudo python -m pytest health-check/tests