name: health-check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check out Git repository
      uses: actions/checkout@v2
    - name: Install Java and Maven
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Package Beer-service
      run: |
        ./beer-api/mvnw -Pprod clean verify -DskipTests
        ./beer-api/mvnw -Pprod verify jib:dockerBuild

    # - name: GitHub Action for Maven
    #   uses: LucaFeger/action-maven-cli@1.1.0
    #   args: -Pprod verify jib:dockerBuild --file beer-api/pom.xml

    # - name: Deploy service to Cloud Run
    #   uses: stefda/action-cloud-run@1.0.0
    #   with:
    #     image: gcr.io/[your-project]/[image]
    #     service: [your-service]
    #     project: [your-project]
    #     region: [gcp-region]
    #     env: [path-to-env-file]
    #     service key: ${{ secrets.GCLOUD_AUTH }}

  test:   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with Pytest
      run: |
        sudo pip install pytest
        sudo pip install pytest-html==1.22.0
        sudo pip install tavern
        sudo pip install pytest-sugar
        sudo python -m pytest health-check/tests